- 👋 Hi, I’m @bexruzcheek
- 👀 I’m interested in ...
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...

<!---
bexruzcheek/bexruzcheek is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
Haqiqiy a1,a2,a3,......an sonlari berilgan. (x-a1)(x-a2)......(x-an) ko'phadining koeffitsiyentlari topilsin.
